### ISSUE TITLE
Send `update` events on association changes

### ISSUE THREAD

**Issue by elliottwilliams** [propershark/shark#13]
Can changes to associated objects trigger an `update` on the object being associated to? Proper is treating associated objects similarly to any other model attributes, so it makes sense on this end to send object-update events for association changes.

**Comment by faultyserver** [comment]
Absolutely. I think that makes sense, since modifying `associated_objects` is affecting the object itself (it is a direct property of Object), and there is already a precedent where we are sending route updates when vehicles join/leave a route.

My only concern for implementation is when updating station associations on a route, or other mass changes. Right now, associations are unitarily mutable (only one association can be created at a time), so appending a generic method that fires an event whenever an association/dissociation occurs could end up firing hundreds of updates to a single route each time an update occurs, which is clearly not desirable.

An obvious solution to that is to manually fire `update` events on objects after the associations have been created, but that's not very dry, and pushes responsibility outward unnecessarily.

The best solution I can come up with right now is to have an `associations_did_change` callback that runs at the end of a Conductor event handler and fires update events for any objects whose associations have changed. The difficulty here is determining that set of objects that have changed.

**Comment by elliottwilliams** [comment]
Could you make `ObjectManager#fire` fire a particular event once per `update` tick? My first thought is to memoize `fire` and clear memoizations at the end of each `update`.

**Comment by faultyserver** [comment]
That's a possibility, though these updates would be originating in Conductor, well after ObjectManager has fired the events.

Partially extending that idea, though: `ObjectManager#fire` currently sends out an object hash (using `Object#to_h`, unsurprisingly), which means there is no meta information about the object (type, `identifying_attribute`, and so on) that Middlewares can use to filter events or handle arguments.

At one point (a few weeks ago now), I was thinking about moving the `to_h` call into Transport, meaning Middlewares would be dealing with Object instances - not hashes - and would thus have access to that information. This would also shift responsibility for calling `to_h` away from any Middleware that creates events and solely into Transport, which is definitely a good thing.

Objects can also implement [`Observable`](http://ruby-doc.org/stdlib-1.9.3/libdoc/observer/rdoc/Observable.html), which would let Conductor listen for changes, and automatically fire updates at the end of an event handler if `associated_objects` had changed on any of them.

I think my only reasoning against this was that Object duplication is ever-so-slightly more expensive than Hash duplication, and now that it clearly has more benefits, I think I'll try implementing this in the near future.

**Comment by faultyserver** [comment]
With the merging of #18, events now have full object instances as arguments (instead of `ObjectManager` calling `to_h`), so they can now carry meta information like a flag for `associations_did_change`, or implement `Observable`.
