### ISSUE TITLE
Implement agency topic RPCs

### ISSUE THREAD

**Issue by elliottwilliams** [propershark/shark#8]
As far as I can tell, the [agency topics](https://github.com/propershark/shark/wiki/WAMP-Events-and-RPCs#agency-topics) specified haven't been implemented. Have you not gotten around to them yet or am I midding something?

And to clarify those calls, will I be calling (for example) `agency.routes` or `citybus.routes`?

**Comment by faultyserver** [comment]
I just haven't gotten around to them yet. It's next on my list after redoing configuration. They'll also be implemented as Crossbar components, meaning their implementation will be in [propershark/crossbar-router](http://github.com/propershark/crossbar-router), not here.

The calls will be the literal strings `agency.routes`, `agency.stations`, and `agency.vehicles`. Since each agency will get their own WAMP realm, naming these with an agency prefix would be redundant and unnecessarily complicated on both our ends. This was the same logic that went into not using the `com.propershark.citybus` prefix on all topics (we never discussed this, I just made that decision at some point).

I'll leave this issue open until they are implemented.

**Comment by faultyserver** [comment]
Closed with propershark/crossbar-router#1.
